services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  auth_db:
    image: postgres:13
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  main_db:
    image: postgres:13
    environment:
      POSTGRES_DB: maindb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - main_data:/var/lib/postgresql/data

  logs_db:
    image: postgres:13
    environment:
      POSTGRES_DB: logsdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - logs_data:/var/lib/postgresql/data

  auth_service:
    build: ./auth_service
    volumes:
      - ./auth_service:/app
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
      - auth_db

  main_service:
    build: ./main_service
    volumes:
      - ./main_service:/app
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
      - main_db

#  chats_service:
#    build: ./chats_service
#    volumes:
#      - ./chats_service:/app
#    ports:
#      - "8003:8000"
#    depends_on:
#      - rabbitmq
#      - main_db

  logging_service:
    build: ./logging_service
    volumes:
      - ./logging_service:/app
    ports:
      - "8004:8000"
    depends_on:
      - rabbitmq
      - logs_db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - auth_db
      - main_db

volumes:
  auth_data:
  main_data:
  logs_data: